# Generated by Django 5.0.6 on 2024-05-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('category', models.CharField(blank=True, choices=[('POPULAR', 'Popular'), ('STARTUPS', 'Startups'), ('SECURITY', 'Security'), ('AI', 'AI'), ('APPS', 'Apps'), ('TECH', 'Tech'), ('TRENDING', 'Trending'), ('FOOD', 'Food')], max_length=100, null=True)),
                ('author', models.CharField(default='', max_length=100)),
                ('picture', models.ImageField(upload_to='author_pics/')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('reading_time', models.IntegerField(help_text='Enter the estimated reading time in minutes')),
                ('content', models.TextField(blank=True, null=True)),
                ('contentTwo', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
