# Generated by Django 5.0.6 on 2024-05-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=models.ImageField(upload_to='author_post/'),
        ),
    ]
